route:
  receiver: default
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h

receivers:
  - name: default
    email_configs:
      - to: admin@mbs-home.ddns.net
        from: alertmanager@mbs-home.ddns.net
        smarthost: mailserver:25
        require_tls: false
        send_resolved: true