server:
  address: tcp://0.0.0.0:9091/

log:
  level: info
  format: text

totp:
  issuer: mbs-home.ddns.net

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "auth.mbs-home.ddns.net"
      policy: bypass
    - domain: "mbs-home.ddns.net"
      policy: one_factor
      subject:
        - "group:admins"
    - domain: "*.mbs-home.ddns.net"
      policy: one_factor
      subject:
        - "group:admins"
    - domain: "vault.mbs-home.ddns.net"
      policy: one_factor
      subject:
        - "group:admins"
    - domain: "home.mbs-home.ddns.net"
      policy: one_factor
      subject:
        - "group:admins"
    - domain: "media.mbs-home.ddns.net"
      policy: bypass  # Allow direct access to Jellyfin for mobile apps
    - domain: "jellyfin.mbs-home.ddns.net"
      policy: bypass  # Allow direct access to Jellyfin for mobile apps

session:
  name: authelia_session
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 8h  # Extended for mobile compatibility
  inactivity: 30m  # Extended for mobile usage
  remember_me: 30d  # Extended remember me period
  same_site: lax  # Better mobile compatibility
  cookies:
    - domain: mbs-home.ddns.net
      authelia_url: https://auth.mbs-home.ddns.net
      default_redirection_url: https://mbs-home.ddns.net

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}
