groups:
  - name: infrastructure
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% on {{ $labels.instance }} for more than 10 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% on {{ $labels.instance }} for more than 10 minutes."

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 85% on {{ $labels.instance }} {{ $labels.mountpoint }}."

      - alert: DiskFull
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk almost full on {{ $labels.instance }}"
          description: "Disk usage is above 95% on {{ $labels.instance }} {{ $labels.mountpoint }}."

  - name: docker_containers
    rules:
      - alert: ContainerKilled
        expr: time() - container_last_seen > 60
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container killed on {{ $labels.instance }}"
          description: "A container has disappeared on {{ $labels.instance }}"

      - alert: ContainerCpuUsageHigh
        expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container CPU usage high on {{ $labels.instance }}"
          description: "Container CPU usage is above 80% on {{ $labels.instance }} for {{ $labels.name }}"

      - alert: ContainerMemoryUsageHigh
        expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container Memory usage high on {{ $labels.instance }}"
          description: "Container Memory usage is above 80% on {{ $labels.instance }} for {{ $labels.name }}"

  - name: web_services
    rules:
      - alert: WebsiteDown
        expr: probe_success == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Website down: {{ $labels.instance }}"
          description: "Website {{ $labels.instance }} is down for more than 5 minutes."

      - alert: WebsiteSlowResponse
        expr: probe_duration_seconds > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Website slow response: {{ $labels.instance }}"
          description: "Website {{ $labels.instance }} is responding slowly (>5s) for more than 5 minutes."

      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon for {{ $labels.instance }}"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 7 days."

      - alert: SSLCertificateExpiringCritical
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate expiring today for {{ $labels.instance }}"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 1 day!"

  - name: media_services
    rules:
      - alert: JellyfinDown
        expr: up{job="jellyfin"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Jellyfin media server is down"
          description: "Jellyfin has been down for more than 5 minutes."

      - alert: MediaServiceDown
        expr: up{job=~"sonarr|radarr|lidarr|bazarr|prowlarr"} == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Media service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 10 minutes."

      - alert: TransmissionDown
        expr: up{job="transmission"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Transmission download client is down"
          description: "Transmission has been down for more than 5 minutes."

  - name: security_services
    rules:
      - alert: AutheliaDown
        expr: up{job="authelia"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Authelia authentication service is down"
          description: "Authelia has been down for more than 2 minutes. This affects access to all protected services."

      - alert: VaultwardenDown
        expr: up{job="vaultwarden"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Vaultwarden password manager is down"
          description: "Vaultwarden has been down for more than 5 minutes."

      - alert: AdguardDown
        expr: up{job="adguard"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "AdGuard DNS server is down"
          description: "AdGuard DNS has been down for more than 5 minutes."

  - name: management_services
    rules:
      - alert: TraefikDown
        expr: up{job="traefik"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Traefik reverse proxy is down"
          description: "Traefik has been down for more than 2 minutes. This affects access to all web services."

      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus monitoring is down"
          description: "Prometheus has been down for more than 5 minutes."

      - alert: PortainerDown
        expr: up{job="portainer"} == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Portainer management interface is down"
          description: "Portainer has been down for more than 10 minutes."

  - name: cloud_services
    rules:
      - alert: NextcloudDown
        expr: up{job="nextcloud"} == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Nextcloud is down"
          description: "Nextcloud has been down for more than 5 minutes."

      - alert: NextcloudDatabaseDown
        expr: up{job="nextcloud-postgres"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Nextcloud database is down"
          description: "Nextcloud PostgreSQL database has been down for more than 2 minutes."

  - name: system_health
    rules:
      - alert: TooManyRestarts
        expr: increase(container_restart_count{container_label_com_docker_compose_project="docker"}[1h]) > 5
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} restarted too many times"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last hour."

      - alert: HighNetworkUsage
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000  # 100MB/s
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High network usage on {{ $labels.instance }}"
          description: "Network usage is above 100MB/s on {{ $labels.instance }} {{ $labels.device }}"

      - alert: SystemLoadHigh
        expr: node_load1 > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High system load on {{ $labels.instance }}"
          description: "System load is {{ $value }} on {{ $labels.instance }}"
