# Dynamic Traefik Configuration for Mac Homelab
# This file contains middleware and additional configuration

http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive"
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "camera=(), microphone=(), geolocation=()"

    # Authelia authentication
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.mbs-home.ddns.net/"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"

    # Nextcloud specific headers
    nextcloud-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Ssl: "on"
          X-Forwarded-Host: "nextcloud.mbs-home.ddns.net"
        customResponseHeaders:
          Referrer-Policy: "no-referrer"

    # Jellyfin specific headers for mobile compatibility
    jellyfin-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "media.mbs-home.ddns.net"
          X-Forwarded-For: "$$remote_addr"

    # Rate limiting
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    # IP whitelist for admin services
    admin-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
          - "10.0.0.0/8"
          - "172.16.0.0/12"

# TLS configuration
tls:
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"