---
# Enhanced Homepage Services Configuration
# For Docker Homelab Stack with Remote Access & Finance Tracking

- Core Infrastructure:
    - Traefik:
        icon: traefik.png
        href: https://traefik.mbs-home.ddns.net
        description: Reverse Proxy & Load Balancer
        widget:
          type: traefik
          url: http://traefik:8080
          username: admin
          password: admin

    - Portainer:
        icon: portainer.png
        href: https://portainer.mbs-home.ddns.net
        description: Docker Management Platform
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_api_key_here

    - AdGuard Home:
        icon: adguard-home.png
        href: https://dns.mbs-home.ddns.net
        description: Network-wide Ad & Tracker Blocking
        widget:
          type: adguard
          url: http://adguard-home:3000
          username: admin
          password: admin

- Security & Access:
    - WireGuard:
        icon: wireguard.png
        href: https://vpn.mbs-home.ddns.net
        description: VPN Server
        widget:
          type: customapi
          url: http://wireguard:51821/api/status
          method: GET

    - Authelia:
        icon: authelia.png
        href: https://auth.mbs-home.ddns.net
        description: Single Sign-On Portal
        widget:
          type: customapi
          url: http://authelia:9091/api/health
          method: GET

    - Vaultwarden:
        icon: bitwarden.png
        href: https://vault.mbs-home.ddns.net
        description: Password Manager
        widget:
          type: customapi
          url: http://vaultwarden:80/alive
          method: GET

- Remote Access & Development:
    - Code Server:
        icon: vscode.png
        href: https://code.mbs-home.ddns.net
        description: VS Code in Browser
        ping: http://code-server:8443
        widget:
          type: customapi
          url: http://code-server:8443/healthz
          method: GET

    - NoMachine:
        icon: nomachine.png
        href: https://remote.mbs-home.ddns.net
        description: Remote Desktop Access
        ping: nomachine:4000

    - File Browser:
        icon: filebrowser.png
        href: https://files.mbs-home.ddns.net
        description: Web File Manager
        ping: http://filebrowser:80

    - Web SSH:
        icon: terminal.png
        href: https://ssh.mbs-home.ddns.net
        description: SSH Terminal Access
        ping: http://webssh:5032

- Financial Management:
    - Firefly III:
        icon: firefly.png
        href: https://money.mbs-home.ddns.net
        description: Personal Finance Manager
        widget:
          type: customapi
          url: http://firefly-iii:8080/api/v1/about
          method: GET
          headers:
            Accept: application/json

- Media Services:
    - Jellyfin:
        icon: jellyfin.png
        href: https://media.mbs-home.ddns.net
        description: Media Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: jellyfin_api_key
          enableBlocks: true
          enableNowPlaying: true

    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.mbs-home.ddns.net
        description: TV Series Management
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: sonarr_api_key

    - Radarr:
        icon: radarr.png
        href: https://radarr.mbs-home.ddns.net
        description: Movie Management
        widget:
          type: radarr
          url: http://radarr:7878
          key: radarr_api_key

    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.mbs-home.ddns.net
        description: Music Management
        widget:
          type: lidarr
          url: http://lidarr:8686
          key: lidarr_api_key

    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.mbs-home.ddns.net
        description: Subtitle Management
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: bazarr_api_key

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.mbs-home.ddns.net
        description: Indexer Manager
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: prowlarr_api_key

- Download Clients:
    - Transmission:
        icon: transmission.png
        href: https://transmission.mbs-home.ddns.net
        description: BitTorrent Client
        widget:
          type: transmission
          url: http://transmission:9091
          username: admin
          password: admin

    - Slskd:
        icon: soulseek.png
        href: https://slskd.mbs-home.ddns.net
        description: Soulseek Client
        ping: http://slskd:5030

- Cloud & Productivity:
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.mbs-home.ddns.net
        description: Personal Cloud Storage
        widget:
          type: nextcloud
          url: http://nextcloud:80
          username: admin
          password: admin-secure-password-2024

- AI & Automation:
    - Open WebUI:
        icon: ai.png
        href: https://ai.mbs-home.ddns.net
        description: AI Chat Interface
        ping: http://open-webui:8080

    - Home Assistant:
        icon: home-assistant.png
        href: https://home.mbs-home.ddns.net
        description: Home Automation
        widget:
          type: homeassistant
          url: http://homeassistant:8123
          key: ha_api_key

- Monitoring & Logs:
    - Grafana:
        icon: grafana.png
        href: https://monitor.mbs-home.ddns.net
        description: Metrics Dashboard
        widget:
          type: grafana
          url: http://grafana:3000
          username: admin
          password: grafana-admin-secure-2024

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.mbs-home.ddns.net
        description: Metrics Collection
        widget:
          type: prometheus
          url: http://prometheus:9090

    - Dozzle:
        icon: dozzle.png
        href: https://logs.mbs-home.ddns.net
        description: Container Logs
        ping: http://dozzle:8080

- System Status:
    - Node Exporter:
        icon: prometheus.png
        description: System Metrics
        widget:
          type: customapi
          url: http://node-exporter:9100/metrics
          method: GET

    - cAdvisor:
        icon: docker.png
        description: Container Metrics
        widget:
          type: customapi
          url: http://cadvisor:8080/metrics
          method: GET

    - Watchtower:
        icon: watchtower.png
        description: Auto-updater
        widget:
          type: customapi
          url: http://watchtower:8080/v1/metrics
          method: GET